version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    open-pull-requests-limit: 6
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/London
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
